### ISSUE TITLE
Standard failing

### ISSUE THREAD

**Issue by dcousens** [dcousens/typeforce#10]
@feross, not sure I understand, can you spot the problem?
[Relevant code](https://github.com/dcousens/typeforce/blob/master/src/index.js#L121).

> standard: Use Use JavaScript Standard Style (https://github.com/feross/standard) 
>   /home/travis/build/dcousens/typeforce/src/index.js:121:22: Expected indentation of 6 characters but found 4.
>   /home/travis/build/dcousens/typeforce/src/index.js:127:20: Expected indentation of 6 characters but found 4.
>   /home/travis/build/dcousens/typeforce/src/index.js:133:20: Expected indentation of 6 characters but found 4.

See https://travis-ci.org/dcousens/typeforce/jobs/74659788

**Comment by feross** [comment]
I think eslint is getting confused because you used a block for your `case` statement, which isn't required. Basically, this:

``` js
    case 'function': {
      if (type(value, strict)) return true

      throw new TypeError(tfErrorString(getFunctionName(type), value))
    }
```

should be:

``` js
    case 'function':
      if (type(value, strict)) return true

      throw new TypeError(tfErrorString(getFunctionName(type), value))
```

**Comment by feross** [comment]
The error message could be more helpful, and/or an unneeded block could/should be flagged. Maybe open an eslint issue about improving the message?

**Comment by dcousens** [comment]
Thanks @feross,  I might file an issue at least for discussion.  Though,  the problem seems clear to me now.
