### ISSUE TITLE
typeforce 1.5.1 breaks bitcoinjs-lib 1.5.8

### ISSUE THREAD

**Issue by williamcotton** [dcousens/typeforce#17]
bitcoinjs-lib@1.5.8 has a dependency "typeforce": "^1.0.0"...

this means that it is forced to upgrade to typeforce 1.5.1... however, typeforce 1.5.1 doesn't seem to work in node 0.12.4

```
$ node node_modules/bitcoinjs-lib/node_modules/typeforce/lib/index.js 
/Users/williamcotton/Projects/fuckthis/node_modules/bitcoinjs-lib/node_modules/typeforce/lib/index.js:45
  Array(value) {
       ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Is this valid JS? Under what version of node?

Please be careful with your semver releases!!!!!!!

**Comment by williamcotton** [comment]
I don't know why this is happening and I don't know what version of node you were targeting with typeforce@1.5.1, but you NEED to push a 1.5.2 that is compatible with the older version that works with 0.12 and you NEED to release the current 1.5.1 as a 2.x.x release... it's the only way not to completely disable anyone (like me) who is on bitcoinjs-lib@1.5.8 and node 0.12.4

**Comment by williamcotton** [comment]
Also, it was a mistake to have bitcoinjs-lib have this "typeforce": "^1.0.0" dependency! Please use explicit versions in the future so as to not cause these kinds of breaking changes.

**Comment by Sjors** [comment]
I agree it would be safer if BitcoinJS limits the requirement to 1.3.\* (and 1.5.\* once this issue is figured out). That's already a ticket: bitcoinjs/bitcoinjs-lib#494

**Comment by mvayngrib** [comment]
+1 waiting for 1.5.2

**Comment by williamcotton** [comment]
The problem is that bitcoinjs-lib 1.5.8 is already published, so there's no going back and fixing it now...

**Comment by Sjors** [comment]
> so there's no going back and fixing it now

I'm not sure if I understand; a new release of BitcoinJS (e.g. 1.5.9) could depend on version 1.3.*. Why would that not work?

**Comment by williamcotton** [comment]
All I'm saying is that bitcoinjs-lib@1.5.8 will continue to be broken along with every module that depends on bitcoinjs-lib@1.5.8, so it really needs to be fixed upstream with a working typeforce@^1.0.0... this typeforce@1.5 release with this ES6/ES2015 needs to be a typeforce@2.0 instead

**Comment by mvayngrib** [comment]
won't bitcoinjs-lib 1.5.8 start working as soon as typeforce 1.5.2 is pushed, as it'll start pulling in 1.5.2?

**Comment by williamcotton** [comment]
That is correct, and then whatever dcousens is trying to do with his typeforce@1.5.x release, he should probably just bump up to typeforce@2.0, so it stops affecting bitcoinjs-lib@1.5.8

**Comment by williamcotton** [comment]
just a tip for the future: changing the language you write a module in is probably worthy of a full version uptick in semver...

**Comment by Sjors** [comment]
BitcoinJS 2.0 is not a trivial change from 1.5.8, depending on how you use it.

**Comment by williamcotton** [comment]
(I edited the above to be more clear because it is very confusing to have these two 1.5 and 2.0 modules in discussion, sorry about that!)

**Comment by dcousens** [comment]
@williamcotton this was passing in the tests (for Node 0.10->4) because the tests use the source code directly. It appears the babel transpiler for the release did **not** compile the code correctly, which has surprised me greatly.

> just a tip for the future: changing the language you write a module in is probably worthy of a full version uptick in semver...

It was always written in ES6.

**Comment by dcousens** [comment]
Published as `1.5.2`, see 2133cc0

**Comment by dcousens** [comment]
@jprichardson, seems I need to work on my tests using the compiled code rather than the transpiler on `mocha`.   Though, to be fair,  I thought there would be no difference...

**Comment by dcousens** [comment]
Reverted use of ES6 entirely in e0241d6,  too many headaches.  Not worth my time for this module. 
No more publish step makes me feel safer anyway.

**Comment by Sjors** [comment]
Thanks! Is there a difference between tag 1.5.5 and tag v1.5.5?

**Comment by dcousens** [comment]
@Sjors well spotted.  Tag `1.5.5` removed, `v1.5.5` was definitively what was published.

**Comment by dcousens** [comment]
Though, the commit hash of `v1.5.5` is not flush with what is in the repository, this is because of the protected branch merge causing the tag to change commit hash on merge... hmmmm.  That is a bit lame.

**Comment by jprichardson** [comment]
> @jprichardson, seems I need to work on my tests using the compiled code rather than the transpiler on mocha. Though, to be fair, I thought there would be no difference...

Yeah, this is the first time I've seen Babel fail? https://github.com/dcousens/typeforce/blob/v1.5.1/package.json#L60 were you using babel5 or babel6? I can't tell from that line. If 6, and if weren't using any plugins/presets and you were using Node v4, the failure then makes sense.

**Comment by dcousens** [comment]
@jprichardson babel6 targets your node version rather than ES5?

**Comment by jprichardson** [comment]
> babel6 targets your node version rather than ES5?

No. Babel6 doesn't target (or do) anything without plugins. This effectively gives the flexibility to selectively target platforms based upon what the platform supports. As a small example, if you wanted to only target Node v4 AND you wanted to use arrows, you wouldn't need the arrow transform plugin, but you would for Node v0.10. But it depends upon the code that you write and the platform that you want to target.

**Comment by jprichardson** [comment]
So,

> If 6, and if weren't using any plugins/presets and you were using Node v4, the failure then makes sense.

The ES6 features that you were using were already supported by Node v4 and probably why you didn't notice any failure if you were using Babel 6 and Node v4 i.e. Babel 6 didn't do anything (assuming you didn't use any plugins/presets).

**Comment by dcousens** [comment]
Ok, it seems I've seriously underestimated how big the breaking changes in babel 6 have been.  Thanks for the insight.

**Comment by dcousens** [comment]
Although, I've not had this issue in other cases...
