### ISSUE TITLE
breaks when uglified with mangle:true

### ISSUE THREAD

**Issue by pgmemk** [dcousens/typeforce#28]
due to the use of fn.name in getFunctionName

(thx for the lib!)

**Comment by mvayngrib** [comment]
+1

**Comment by dcousens** [comment]
Interesting, is this using `uglifyjs`?  If so, I'll see if I can replicate a test case ASAP :+1:

**Comment by mvayngrib** [comment]
@dcousens were you able to replicate the issue?

**Comment by dcousens** [comment]
@mvayngrib sorry,  I am not able to replicate this issue.
I've uglified the library using `uglifyjs` and then tested importing it,  with no issues.

Is there anything else I need to do?

**Comment by mvayngrib** [comment]
@dcousens sorry for the radio silence. Here's an example that breaks for me

``` js
// fnname.js
var typeforce = require('typeforce')

function Blah () {}

var blah = new Blah()
typeforce('Blah', blah)
```

``` bash
browserify fnname.js | uglifyjs -c -m > fnname.min.js && node fnname.min.js
```

``` bash
(function (exports, require, module, __filename, __dirname) { !function t(r,e,n){function i(u,a){if(!e[u]){if(!r[u]){var f="function"==typeof require&&require;if(!a&&f)return f(u,!0);if(o)return o(u,!0);var s=new Error("Cannot find module '"+u+"'");throw s.code="MODULE_NOT_FOUND",s}var h=e[u]={exports:{}};r[u][0].call(h.exports,function(t){var e=r[u][1][t];return i(e?e:t)},h,h.exports,t,r,e,n)}return e[u].exports}for(var o="function"==typeof require&&require,u=0;u<n.length;u++)i(n[u]);return i}({1:[function(t,r,e){function n(){}var i=t("./"),o=new n;i("Blah",o)},{"./":2}],2:[function(t,r,e){(function(t){function e(t){if(void 0===t)return"";if(null===t)return"";var r=t.constructor.toString().match(/function (.*?)\(/);return r?r[1]:null}function n(r,n){r.split("|").forEach(function(i){switch(i){case"Array":if(null!==n&&void 0!==n&&n.constructor===Array)return;break;case"Boolean":if("boolean"==typeof n)return;break;case"Buffer":if(t.isBuffer(n))return;break;cas

TypeError: Expected Blah, got n [object Object]
    at o (/Users/tenaciousmv/Code/typeforce/fnname.min.js:1:1468)
    at /Users/tenaciousmv/Code/typeforce/fnname.min.js:1:1170
    at Array.forEach (native)
    at Object.n [as string] (/Users/tenaciousmv/Code/typeforce/fnname.min.js:1:775)
    at r.exports (/Users/tenaciousmv/Code/typeforce/fnname.min.js:1:1703)
    at Object.a.1../ (/Users/tenaciousmv/Code/typeforce/fnname.min.js:1:557)
    at i (/Users/tenaciousmv/Code/typeforce/fnname.min.js:1:316)
    at t (/Users/tenaciousmv/Code/typeforce/fnname.min.js:1:483)
    at Object.<anonymous> (/Users/tenaciousmv/Code/typeforce/fnname.min.js:1:500)
    at Module._compile (module.js:435:26)
```

**Comment by dcousens** [comment]
@mvayngrib right, that is simply a risk of uglify.
Due to it mangling the name `Blah`.

This is an underlying issue with using `quacksLike`, if you mangle the names,  its inherently risky.

You're best bet is to exclude `Blah` from being mangled in uglify-js using:

``` bash
uglifyjs --reserved-names Blah
```

Alternatively, you can make your own type function (with all of its inherent risks):

``` javascript
function BlahType (value) { return value instanceof Blah }
typeforce(BlahType, blah)
```

or

``` javascript
typeforce(v => v instanceof Blah, blah)
```

I might make a `typeforce.instanceOf(...)` type function so you can do `typeforce(typeforce.instanceOf(Blah), blah)` to make this a bit simpler.

**Comment by dcousens** [comment]
I might make a `typeforce.instanceOf(...)` type function so you can do `typeforce(typeforce.instanceOf(Blah), blah)`,  but otherwise I don't see any easy way around this.

**Comment by dcousens** [comment]
Alternate alternatively:  `typeforce(Blah.name, blah)` might work.

(`Blah.toString().match(/function (.*?)\s*\(/)[1]` if `name` is undefined).

**Comment by mvayngrib** [comment]
right, that's more or less what i've been doing. It is what it is :)

**Comment by dcousens** [comment]
I'm going to close this as `wontfix`,  but it isnt' because I don't want to fix it,  I just don't think we can due to the nature of it.

Maybe we should put a warning in the README?

**Comment by mvayngrib** [comment]
@dcousens yes to wontfix, yes to warning. Btw, i noticed this issue when I was uglifying bitcoinjs-lib, an older version, but i think the latest one uses quacksLike (which as you say has the same issue)

**Comment by dcousens** [comment]
@mvayngrib ah!  You probably should have noticed the warning that is already in the [bitcoinjs-lib README](https://github.com/bitcoinjs/bitcoinjs-lib#browser) then :smile:

**Comment by mvayngrib** [comment]
@dcousens haha, you got me, totally missed that
