### ISSUE TITLE
Error.captureStackTrace is undefined

### ISSUE THREAD

**Issue by dcousens** [dcousens/typeforce#49]
Ref https://github.com/bitcoinjs/bitcoinjs-lib/issues/976#issuecomment-385319340

It is V8 specific.

**Comment by dcousens** [comment]
Cannot reproduce...

**Comment by takunee** [comment]
ReactNative on android with Huawei mate9 .   reproduce

**Comment by dcousens** [comment]
https://github.com/dcousens/typeforce/commit/eed6e708399f22b3e01db2a077a8b020abfccab5
